name: Python Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install kivy[full]
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Install libmtdev.so.1
        run: sudo apt-get install libmtdev-dev

      - name: Run main script
        run: |
          python main.py

      - name: Run tests
        run: |
          python -m unittest discover tests
