name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      #used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path

      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install kivy
          python -m pip install kivy_garden.mapview
          python -m pip install geopy
          python -m pip install pyperclip
          python -m pip install requests
          python -m pip install overpass
          python -m pip install Pillow
          python -m pip install pygame
          python -m pip install buildozer
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
          sudo apt install libgl1-mesa-dev
          sudo apt-get install xclip xsel
          sudo apt-get install aidl
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: pip3 install --user --upgrade Cython==0.29.33 virtualenv; buildozer android debug
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
