name: Python Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Gib hier deine Python-Version an

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run build script
        run: |
          # Führe hier deinen Build-Prozess aus
          python build_script.py  # Ersetze dies durch deinen eigenen Build-Befehl

      - name: Run tests
        run: |
          # Führe hier deine Tests aus
          python -m unittest discover tests  # Ersetze dies durch deine eigenen Testbefehle
